#!/usr/bin/env ruby
# encoding: utf-8

require File.expand_path("../../config/environment",  __FILE__)

users = ["Barack Obama", "Vladimir Putin", "Hu Jintao", "Angela Merkel",
   "Bill Gates", "Abdullah bin Abdul Aziz al Saud", "Pope Benedict XVI",
   "Ben Bernanke", "Mark Zuckerberg", "David Cameron", "Sonia Gandhi",
   "Mario Draghi", "Nicolas Sarkozy", "Wen Jiabao", "Zhou Xiaochuan",
   "Hillary Clinton", "Michael Bloomberg", "Timothy Geithner",
   "Manmohan Singh", "Warren Buffett", "Silvio Berlusconi",
   "Dilma Rousseff", "Carlos Slim Helu", "Rupert Murdoch",
   "Benjamin Netanyahu", "Ali Hoseini-Khamenei", "Michael Duke",
   "Jeffrey Immelt", "Zhou Yongkang", "Sergey Brin", "Larry Page",
   "Ali Al-Naimi", "Rostam Ghasemi", "Lou Jiwei", "Ashfaq Parvez Kayani",
   "Mukesh Ambani", "Masaaki Shirakawa", "Kim Jong-il", "Ban Ki-moon",
   "Christine Lagarde", "Jeff Bezos", "Jamie Dimon", "Robin Li",
   "Lloyd Blankfein", "Li Ka-shing", "Charles Koch", "David Koch",
   "Rex Tillerson", "Lakshmi Mittal", "Recep Erdogan", "Robert Zoellick",
   "Bill Clinton", "Dalai Lama", "Larry Fink", "Khalifa bin Zayed Al-Nahyan",
   "Bill Gross", "Joaquin Guzman Loera", "Ahmed Shuja Pasha",
   "Dawood Ibrahim Kaskar", "Tim Cook", "Dmitry Medvedev", "Masayoshi Son",
   "Azim Premji", "Yoshihiko Noda", "Joseph Blatter", "Jill Abramson",
   "Bernard Arnault", "Sebastian Pinera", "John Boehner", "Jacques Rogge",
   "Xi Jinping", "Alisher Usmanov"]

$redis.del("users")
users.each do |user|
  $redis.lpush("users", user)
end