#!/usr/bin/env ruby
# encoding: utf-8

require File.expand_path("../../config/environment",  __FILE__)

users = [
  "Dear Leader", "Kim Jong-il", "Kim Il-sung", "Kim Jong-un", "Dennis Rodman", "Great Leader", "Generalissimo", "Eternal President"
]

$redis.multi
$redis.del("users")
users.each do |user|
  $redis.lpush("users", user)
end
$redis.exec